#!/usr/bin/env bash
set -euo pipefail

ACTION=${1:-"up"} # up | down | ps
MODE=${MODE:-"domain"} # domain | local | ip

APP_DOMAIN=${APP_DOMAIN:-""}
AUTH_DOMAIN=${AUTH_DOMAIN:-""}
ACME_EMAIL=${ACME_EMAIL:-""}
FLOWLET_IP=${FLOWLET_IP:-""}
FLOWLET_PUBLIC_HOST=${FLOWLET_PUBLIC_HOST:-""}
KEYCLOAK_PUBLIC_URL=${KEYCLOAK_PUBLIC_URL:-""}
KEYCLOAK_FRONTEND_URL=${KEYCLOAK_FRONTEND_URL:-""}
VITE_KEYCLOAK_URL=${VITE_KEYCLOAK_URL:-""}
FLOWLET_OIDC_ISSUER=${FLOWLET_OIDC_ISSUER:-""}
FLOWLET_HOSTS=${FLOWLET_HOSTS:-""}
FLOWLET_FRONTEND_SCHEME=${FLOWLET_FRONTEND_SCHEME:-""}
FLOWLET_FRONTEND_PORT=${FLOWLET_FRONTEND_PORT:-""}
FLOWLET_BACKEND_SCHEME=${FLOWLET_BACKEND_SCHEME:-""}
FLOWLET_BACKEND_PORT=${FLOWLET_BACKEND_PORT:-""}
FLOWLET_REALM=${FLOWLET_REALM:-"flowlet"}
FLOWLET_CLIENT_ID=${FLOWLET_CLIENT_ID:-"flowlet-app"}
FLOWLET_MODEL_HUB_KEY=${FLOWLET_MODEL_HUB_KEY:-""}
KEYCLOAK_ADMIN_USER=${KEYCLOAK_ADMIN_USER:-"admin"}
KEYCLOAK_ADMIN_PASSWORD=${KEYCLOAK_ADMIN_PASSWORD:-"admin123"}
FLOWLET_ENABLE_OFFLINE_ACCESS=${FLOWLET_ENABLE_OFFLINE_ACCESS:-"true"}

ENV_FILE="docker/.env.flowlet"
COMPOSE_FILE=""

log() { printf "[docker] %s\n" "$1"; }
fail() { printf "[docker][error] %s\n" "$1" >&2; exit 1; }

case "${MODE}" in
  domain)
    [ -n "${APP_DOMAIN}" ] || fail "MODE=domain requires APP_DOMAIN"
    [ -n "${AUTH_DOMAIN}" ] || fail "MODE=domain requires AUTH_DOMAIN"
    [ -n "${ACME_EMAIL}" ] || fail "MODE=domain requires ACME_EMAIL"
    COMPOSE_FILE="docker/docker-compose.full.yml"
    ;;
  local)
    COMPOSE_FILE="docker/docker-compose.local.yml"
    ;;
  ip)
    [ -n "${FLOWLET_IP}" ] || fail "MODE=ip requires FLOWLET_IP"
    COMPOSE_FILE="docker/docker-compose.ip.yml"
    ;;
  *)
    fail "unknown MODE: ${MODE} (use domain|local|ip)"
    ;;
esac

if [ "${MODE}" = "ip" ]; then
  FLOWLET_PUBLIC_HOST="${FLOWLET_PUBLIC_HOST:-${FLOWLET_IP}}"
  KEYCLOAK_PUBLIC_URL="${KEYCLOAK_PUBLIC_URL:-https://${FLOWLET_PUBLIC_HOST}:8443}"
  KEYCLOAK_FRONTEND_URL="${KEYCLOAK_FRONTEND_URL:-${KEYCLOAK_PUBLIC_URL}}"
  FLOWLET_OIDC_ISSUER="${FLOWLET_OIDC_ISSUER:-${KEYCLOAK_PUBLIC_URL}/realms/${FLOWLET_REALM}}"
  VITE_KEYCLOAK_URL="${VITE_KEYCLOAK_URL:-${KEYCLOAK_PUBLIC_URL}/realms/${FLOWLET_REALM}}"
  FLOWLET_HOSTS="${FLOWLET_HOSTS:-${FLOWLET_PUBLIC_HOST},localhost}"
  FLOWLET_FRONTEND_SCHEME="${FLOWLET_FRONTEND_SCHEME:-https}"
  FLOWLET_FRONTEND_PORT="${FLOWLET_FRONTEND_PORT:-5173}"
  FLOWLET_BACKEND_SCHEME="${FLOWLET_BACKEND_SCHEME:-https}"
  FLOWLET_BACKEND_PORT="${FLOWLET_BACKEND_PORT:-5173}"
  APP_DOMAIN="${APP_DOMAIN:-${FLOWLET_PUBLIC_HOST}}"
  AUTH_DOMAIN="${AUTH_DOMAIN:-${FLOWLET_PUBLIC_HOST}}"
fi

cat <<EOF > "${ENV_FILE}"
APP_DOMAIN=${APP_DOMAIN}
AUTH_DOMAIN=${AUTH_DOMAIN}
ACME_EMAIL=${ACME_EMAIL}
FLOWLET_PUBLIC_HOST=${FLOWLET_PUBLIC_HOST}
KEYCLOAK_PUBLIC_URL=${KEYCLOAK_PUBLIC_URL}
KEYCLOAK_FRONTEND_URL=${KEYCLOAK_FRONTEND_URL}
VITE_KEYCLOAK_URL=${VITE_KEYCLOAK_URL}
FLOWLET_OIDC_ISSUER=${FLOWLET_OIDC_ISSUER}
FLOWLET_HOSTS=${FLOWLET_HOSTS}
FLOWLET_FRONTEND_SCHEME=${FLOWLET_FRONTEND_SCHEME}
FLOWLET_FRONTEND_PORT=${FLOWLET_FRONTEND_PORT}
FLOWLET_BACKEND_SCHEME=${FLOWLET_BACKEND_SCHEME}
FLOWLET_BACKEND_PORT=${FLOWLET_BACKEND_PORT}
FLOWLET_REALM=${FLOWLET_REALM}
FLOWLET_CLIENT_ID=${FLOWLET_CLIENT_ID}
FLOWLET_MODEL_HUB_KEY=${FLOWLET_MODEL_HUB_KEY}
KEYCLOAK_ADMIN_USER=${KEYCLOAK_ADMIN_USER}
KEYCLOAK_ADMIN_PASSWORD=${KEYCLOAK_ADMIN_PASSWORD}
FLOWLET_ENABLE_OFFLINE_ACCESS=${FLOWLET_ENABLE_OFFLINE_ACCESS}
EOF

case "${ACTION}" in
  up)
    log "starting (${MODE}) using ${COMPOSE_FILE}"
    docker compose -f "${COMPOSE_FILE}" --env-file "${ENV_FILE}" up -d --build
    ;;
  down)
    log "stopping (${MODE}) using ${COMPOSE_FILE}"
    if [ "${CLEAN_DATA:-false}" = "true" ]; then
      docker compose -f "${COMPOSE_FILE}" --env-file "${ENV_FILE}" down -v
    else
      docker compose -f "${COMPOSE_FILE}" --env-file "${ENV_FILE}" down
    fi
    ;;
  ps)
    docker compose -f "${COMPOSE_FILE}" --env-file "${ENV_FILE}" ps
    ;;
  *)
    fail "unknown ACTION: ${ACTION} (use up|down|ps)"
    ;;
esac
